### ISSUE TITLE
Problem with class: class org.owasp.csrfguard.config.PropertiesConfigurationProvider

### ISSUE THREAD

**Issue by 40rn05lyv** [aramrami/OWASP-CSRFGuard#20]
I downloaded OWASP-CSRFGuard and tried it with minimal `Owasp.CsrfGuard.properties` configuration (as in https://www.owasp.org/index.php/CSRFGuard_3_Configuration).

When starting Tomcat the exception is thrown:

```
java.lang.RuntimeException: Problem with class: class org.owasp.csrfguard.config.PropertiesConfigurationProvider
at org.owasp.csrfguard.util.CsrfGuardUtils.newInstance(CsrfGuardUtils.java:798)
at org.owasp.csrfguard.CsrfGuard.retrieveNewConfig(CsrfGuard.java:110)
at org.owasp.csrfguard.CsrfGuard.config(CsrfGuard.java:86)
at org.owasp.csrfguard.CsrfGuard.getLogger(CsrfGuard.java:134)
at org.owasp.csrfguard.CsrfGuard.toString(CsrfGuard.java:495)
at org.owasp.csrfguard.CsrfGuardServletContextListener.printConfigIfConfigured(CsrfGuardServletContextListener.java:101)
at org.owasp.csrfguard.CsrfGuardServletContextListener.contextInitialized(CsrfGuardServletContextListener.java:86)
at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4729)
at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5167)
at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1768)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.InstantiationException: org.owasp.csrfguard.config.PropertiesConfigurationProvider
at java.lang.Class.newInstance(Class.java:427)
at org.owasp.csrfguard.util.CsrfGuardUtils.newInstance(CsrfGuardUtils.java:793)
... 19 more
Caused by: java.lang.NoSuchMethodException: org.owasp.csrfguard.config.PropertiesConfigurationProvider.<init>()
at java.lang.Class.getConstructor0(Class.java:3082)
at java.lang.Class.newInstance(Class.java:412)
... 20 more
```

Solution:

Add following line in Owasp.CsrfGuard.properties:
`org.owasp.csrfguard.configuration.provider.factory = org.owasp.csrfguard.config.PropertiesConfigurationProviderFactory`

It must be also be fixed in source code: change in CsrfGuard (https://github.com/aramrami/OWASP-CSRFGuard/blob/master/csrfguard/src/main/java/org/owasp/csrfguard/CsrfGuard.java#L106) the 106th line:
from 

```
PropertiesConfigurationProvider.class.getName()
```

to 

```
PropertiesConfigurationProviderFactory.class.getName()
```

**Comment by hsn10** [comment]
create pull request with fix

**Comment by afattahi54** [comment]
@hsn10 Thanks for fix. Is this fix available on version 3.1.0 !?

I have downloaded the 3.1.0 and face the error. The  

````
org.owasp.csrfguard.configuration.provider.factory = org.owasp.csrfguard.config.PropertiesConfigurationProviderFactory

did not help either

**Comment by ChrisRovers** [comment]
Also looking for a fixed released version, as we'd prefer to pick up this from Maven Central...

**Comment by nbluis** [comment]
Hello.

Please, any updates on this?

**Comment by glitchcube** [comment]
I can see that this issue is merged to the master-branch. I assume this feature will be available in the next release of CSRFGuard.

**Comment by aramrami** [comment]
Yes of course. I need to fix all open issues.
