### ISSUE TITLE
Javascript error, no token injection

### ISSUE THREAD

**Issue by vdl1992** [aramrami/OWASP-CSRFGuard#45]
Hi, 

I have implemented the csrf guard in a Java Spring web project and it is checking for tokens upon POST. However, these tokens do not get injected into forms. I'm using the javascript to inject the tokens but when I load a page I get the following error in the browser console.

'Uncaught SyntaxError: Unexpected token % csrfguard.js:194'

Does anyone know what I might do wrong or what the problem is?

Kind regards

**Comment by 40rn05lyv** [comment]
Probably you didn't configure JavaScriptServlet

**Comment by vdl1992** [comment]
Hi, Thanks for the quick reply. I did not use the JavaScriptServlet mapping because it could not find the javascript file, instead I linked the file in the html like this.

'<script src="//${basescript}/scripts/csrfguard.js"></script>'

Do you explicitly need to use the servletmapping manner?

**Comment by 40rn05lyv** [comment]
csrfguard.js contains variables like %DOMAIN_STRICT%, %INJECT_ATTRIBUTES% etc. and they will be replaced with real values only when JavascriptServlet is used.

**Comment by 40rn05lyv** [comment]
Location of js file can be specified in Owasp.CsrfGuard.properties with org.owasp.csrfguard.JavascriptServlet.sourceFile key

**Comment by vdl1992** [comment]
Okay, thank you very much. I will try to get the servletmapping working then.

Kind regards

**Comment by vdl1992** [comment]
I configured the mapping as seen in the test project on this git but I keep getting the following error.
Failed to load resource: the server responded with a status of 404 (Not Found) http://localhost/JavaScriptServlet

This is my servlet mapping.

<servlet>
		<servlet-name>JavaScriptServlet</servlet-name>
		<servlet-class>org.owasp.csrfguard.servlet.JavaScriptServlet</servlet-class>
	</servlet>

	<servlet-mapping>
		<servlet-name>JavaScriptServlet</servlet-name>
		<url-pattern>/JavaScriptServlet</url-pattern>
	</servlet-mapping>

And this is how I reffer it in the html.

src="/JavaScriptServlet"

**Comment by 40rn05lyv** [comment]
Just try to run `csrfguard-test` project and then compare it with your project. I'm sure you missed smth.

**Comment by vdl1992** [comment]
Allright, turns out there was another mapping conflicting with the JavaScriptServlet one. It all works now, thanks for your help! :d

**Comment by AnilKumarReddyBelum** [comment]
I configured the CSRF GUARD protection to my spring mvc web application.
I configured every thing. but when i deploy the war file into weblogic environemnt i am getting the below error.

******************
CONFIGURATION
********************
<servlet>
     <servlet-name>JavaScriptServlet</servlet-name>
     <servlet-class>org.owasp.csrfguard.servlet.JavaScriptServlet</servlet-class>
   <init-param>
         <param-name>source-file</param-name>
         <param-value>/WEB-INF/csrfguard.js</param-value>
     </init-param>
     <init-param>
         <param-name>inject-into-forms</param-name>
         <param-value>true</param-value>
     </init-param>
     <init-param>
         <param-name>inject-into-attributes</param-name>
         <param-value>true</param-value>
     </init-param>
    <init-param>
         <param-name>domain-strict</param-name>
         <param-value>false</param-value>
    </init-param>
    <init-param>
         <param-name>referer-pattern</param-name>
         <param-value>.*</param-value>
    </init-param> 
</servlet>
<servlet-mapping>
     <servlet-name>JavaScriptServlet</servlet-name>
     <url-pattern>/JavaScriptServlet</url-pattern>
</servlet-mapping>

********************************
ERROR
********************************

]] Root cause of ServletException.
java.lang.NullPointerException
     at java.io.FileInputStream.<init>(FileInputStream.java:116)
     at java.io.FileInputStream.<init>(FileInputStream.java:79)
     at org.owasp.csrfguard.servlet.JavaScriptServlet.readFileContent(JavaScriptServlet.java:220)
     at org.owasp.csrfguard.servlet.JavaScriptServlet.init(JavaScriptServlet.java:91)
     at weblogic.servlet.internal.StubSecurityHelper$ServletInitAction.run(StubSecurityHelper.java:299)
     at weblogic.servlet.internal.StubSecurityHelper$ServletInitAction.run(StubSecurityHelper.java:250)
     at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
     at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
     at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
     at weblogic.servlet.internal.StubSecurityHelper.initServletInstance(StubSecurityHelper.java:94)
     at weblogic.servlet.internal.StubSecurityHelper.createServlet(StubSecurityHelper.java:82)
     at weblogic.servlet.internal.StubLifecycleHelper.createOneInstance(StubLifecycleHelper.java:74)
     at weblogic.servlet.internal.StubLifecycleHelper.<init>(StubLifecycleHelper.java:60)
     at weblogic.servlet.internal.StubLifecycleHelper.<init>(StubLifecycleHelper.java:34)
     at weblogic.servlet.internal.ServletStubImpl.initStubLifecycleHelper(ServletStubImpl.java:624)
     at weblogic.servlet.internal.ServletStubImpl.prepareServlet(ServletStubImpl.java:565)
     at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:281)
     at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25)
     at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:74)
     at org.owasp.csrfguard.CsrfGuardFilter.doFilter(CsrfGuardFilter.java:82)
     at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:74)
     at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3288)
     at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3254)
     at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
     at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
     at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57)
     at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2163)
     at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2089)
     at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2074)
     at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1513)
     at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:254)
     at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
     at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)


Could you please let us know what i am missing in the above configuration?
And the above code is working in my local weblogic 12 environemnt but the problem with UNIX weblogic 12 environemnt.

Please help me out here !

**Comment by AnilKumarReddyBelum** [comment]
I am using the weblogic 11.3.6 do i need to set any thing explicitly to make CSRF GUARD works ?

**Comment by vdevpriya** [comment]
Facing the same issue. Using weblogic 12.2.1.2. What to do??

**Comment by shogan94** [comment]
When I try and use the dynamic javascript injection, I add the script tag to the bottom of my page and it successfully calls `/JavaScriptServlet` but then when it makes the POST it gets a 404. Is that something I have to setup or should already be setup? Thanks

**Comment by upolhasan** [comment]
I am having problem with dynamic javascript injection with csrfguard 3.1.0. I am able to call `<script src="/JavaScriptServlet"></script>` but I'm getting error 500 and here is the error:

`Jun 11, 2018 3:36:21 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [JavaScriptServlet] in context with path [/mysite] threw exception
java.lang.NullPointerException
	at org.owasp.csrfguard.servlet.JavaScriptServlet.doGet(JavaScriptServlet.java:103)`

and when debugged through the code:
`
	public void doGet(HttpServletRequest request, HttpServletResponse response) throws IOException {
		String refererHeader = request.getHeader("referer");
		boolean hasError = false;
		Pattern javascriptRefererPattern = CsrfGuard.getInstance().getJavascriptRefererPattern();
		if(refererHeader != null && !javascriptRefererPattern.matcher(refererHeader).matches())
`
 I found that `javascriptRefererPattern` is set as null all the time.

Is this a bug or there are some configuration that I'm missing?

When starting server I get this in the console:

`INFO: Printing properties before Javascript servlet, note, the javascript properties might not be initialized yet: 
*****************************************************
* Owasp.CsrfGuard Properties
*
* Logger: org.owasp.csrfguard.log.JavaLogger
* NewTokenLandingPage: null
* PRNG: SHA1PRNG
* SessionKey: OWASP_CSRFTOKEN
* TokenLength: 32
* TokenName: OWASP_CSRFTOKEN
* Ajax: true
* Rotate: false
* Javascript cache control: null
* Javascript domain strict: false
* Javascript inject attributes: false
* Javascript inject forms: false
* Javascript referer pattern: null
* Javascript referer match domain: false
* Javascript source file: null
* Javascript X requested with: null
* Protected methods: Empty HashSet
* Protected pages size: 0
* Unprotected methods: Empty HashSet
* Unprotected pages size: 0
* TokenPerPage: true
* Enabled: true
* ValidateWhenNoSessionExists: true
* Action: org.owasp.csrfguard.action.Log
*	Parameter: Message = potential cross-site request forgery (CSRF) attack thwarted (user:%user%, ip:%remote_ip%, method:%request_method%, uri:%request_uri%, error:%exception_message%)
* Action: org.owasp.csrfguard.action.Redirect
*	Parameter: Page = /mysite/error.html
* Action: org.owasp.csrfguard.action.Rotate
*****************************************************`

I think the configuration is not working properly. Please help. Thank you.

**Comment by upolhasan** [comment]
Hi @shogan94 , make sure you double check your properties file and cross check with your web.xml values, e.g. the exact location of the csrfguard.js. Also make sure from the web.xml that you are successfully pointing to the .properties file. Also try to get the clue from the server side logs. Also try to call the servrlet the first thing in the body tag: `<body>	

    <script src="JavaScriptServlet"></script>`

Hope this helps.

**Comment by shogan94** [comment]
@upolhasan thanks. I know the things are in the right place because everything else works and the script loads, but when the script does the POST to get the token it gets a 404.  The GET works fine and returns the script

**Comment by upolhasan** [comment]
Hi @shogan94, on what resource you're getting 404? Are you using the token landing page? Try without it to see if you still get 404.
