### ISSUE TITLE
weblogic unable to load CSRFGuard properties files

### ISSUE THREAD

**Issue by Vzsriram11** [aramrami/OWASP-CSRFGuard#68]
Hi,
I am try to incorporate CSRFguard into my application.I downloaded CSRFguard-3.1.0 jar, added it to my application's EAR (lib dir) and added the Owasp.CsrfGuard.properties under WEB-INF dir in my web application's WAR (WAR is inside the EAR) file . I configured the web.xml as follows.
When I deploy my application I get the error:
**Caused By: java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at org.owasp.csrfguard.CsrfGuardServletContextListener.getResourceStream(CsrfGuardServletContextListener.java:120)**

I tried various options such as by specifying the absolute path as a JVM level class path argument. But it didn't help. THe only time it works is if I place the .properties file in the domain dir. I don't have that option in production. Hence I need to get it working through the class path or WEB-INF option.
 COuld you please assist ?  I have attached the excerpts from web.xml

options tried:
1. APP_CLASSPATH=/REAL_PATH/Owasp.CsrfGuard.properties (didn't work)
2.  -DOwasp.CsrfGuard.Config=/REAL_PATH/Owasp.CsrfGuard.properties  (didn't work)
3. WEB-INF/Owasp.CsrfGuard.properties with web.xml entry as below
web.xml excerpts:
[web_xml_excerpts.txt](https://github.com/aramrami/OWASP-CSRFGuard/files/759342/web_xml_excerpts.txt)
Exception:

       at weblogic.management.deploy.internal.ConfiguredDeployments.activate(ConfiguredDeployments.java:169)
        at weblogic.management.deploy.internal.ConfiguredDeployments.deploy(ConfiguredDeployments.java:123)
        at weblogic.management.deploy.internal.DeploymentServerService.resume(DeploymentServerService.java:180)
        at weblogic.management.deploy.internal.DeploymentServerService.start(DeploymentServerService.java:96)
        at weblogic.t3.srvr.SubsystemRequest.run(SubsystemRequest.java:64)
        at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
        at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
**Caused By: java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)**
        at org.owasp.csrfguard.CsrfGuardServletContextListener.getResourceStream(CsrfGuardServletContextListener.java:120)
        at org.owasp.csrfguard.CsrfGuardServletContextListener.contextInitialized(CsrfGuardServletContextListener.java:67)
        at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:481)
        at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)

**Comment by MariaJavaDev** [comment]
Hello. I had the same problem with loading the Owasp.CsrfGuard.properties file.
It worked when I put it the WEB-INF/classes of the war. And point it in the web.xml just as
<param-value>Owasp.CsrfGuard.properties</param-value>

**Comment by antoniomacri** [comment]
If using Maven, the correct place should be `src/main/resources`, which will end up in `WEB-INF/classes` in the WAR.
